num1=int(input("enter first number:"))
num2=int(input("enter second number:"))
addition=num1+num2
substraction=num1-num2
multiplication=num1*num2
division=num1/num2
print(num1,"+",num2,"=",addition)
print(num1,"-",num2,"=",substraction)
print(num1,"/",num2,"=",division)
